# Generated by Django 2.1.5 on 2019-02-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='completd',
            new_name='completed',
        ),
    ]
